### ISSUE TITLE
Loss of constant precision

### ISSUE THREAD

**Issue by therontarigo** [laurentlb/Shader_Minifier#114]
My application requires the full IEEE754 precision as supported by the GPUs I target (with `precision highp float`).  I have a constant in the shader source:
`float pi = 3.1415927;`
Shader Minifier translates this to
`float M=3.14159;`
resulting in measurably altered results.

Furthermore there is another bug when trying to use a workaround:
```
float pi =
//[
3.1415927;
//]
```
results in a parse error.  I must wrap the entirety of the constant definition in `//[` `//]` which has the unwanted effect of preventing Shader Minifier from shortening these constant names.

For the example case here, I can use `acos(-1.)` as my `pi` constant, but for other high precision constants the limitation stands.

**Comment by laurentlb** [comment]
Thanks for the report. That's indeed a bug that we should look into.

As a workaround, you can define a macro:
```c
#define pi 3.1415927
```
