### ISSUE TITLE
Unexpected behavior

### ISSUE THREAD

**Issue by Andreslav** [laurentlb/Shader_Minifier#116]
Input
```
//[
float N = 1.79284291400159;
//]
float N2 = 1.79284291400159;
```
Output
`float N=1.79284291400159;float N=1.79284;`

You can quickly reproduce the example here http://www.ctrl-alt-test.fr/minifier/index

**Comment by laurentlb** [comment]
Workaround:

```c
#define N 1.79284291400159
float N2 = 1.79284291400159;
```

The syntax `//[` will tell the Minifier to ignore the content, so it's unsafe if it declares a short variable name. The Minifier has a (limited) understanding of macros and can avoid the conflicts.
