### ISSUE TITLE
Arrays not supported

### ISSUE THREAD

**Issue by stfx** [laurentlb/Shader_Minifier#13]
This tool is really cool however the following throws an exception upon getting to the first bracket `[`:
```glsl
const vec2 samples[10] = vec2[](
vec2(-0.5798373, -0.6431335),
vec2(-0.905221, -0.124952),
vec2(-0.2680226, 0.254136),
vec2(-0.01519084, -0.5156112),
vec2(-0.7712643, 0.4174358),
vec2(0.4850016, 0.1596012),
vec2(0.6443742, -0.5418636),
vec2(-0.3830979, 0.8917095),
vec2(0.4932076, 0.7231117),
vec2(0.2750384, -0.9251713)
);
```

The above code in particular is used to iterate over samples in a poisson disk which is a common way to smoothly filter shadow maps. Example: http://www.sunandblackcat.com/tipFullView.php?l=eng&topicid=35&topic=Shadow-Mapping-Poisson-VSM-ESM-PCF

The only workaround I have found is to remove the array by manually unrolling the loop where those values are used which is non-ideal for performance and filesize especially for more than a few samples.

**Comment by laurentlb** [comment]
It's a problem in the parser.

Workaround:
```
const vec2 samples[10] = vec2[10](...)
```

**Comment by stfx** [comment]
Thanks for your reply however that still does not seem to work if you are using a const for the sample count like so:
```glsl
const int ShadowSamples = 10;
const vec2 samples[ShadowSamples] = vec2[ShadowSamples](
```
as the `ShadowSamples` in `samples[ShadowSamples]` will not get replaced with the renamed variable name resulting in `const vec2 d[ShadowSamples]=vec2[s]` which does not compile
