### ISSUE TITLE
Add stdout as output option

### ISSUE THREAD

**Issue by Lutymane** [laurentlb/Shader_Minifier#140]
Hello,

I was wondering if it'd be possible to add an output option to print the minified shader into `stdout`, which would allow piping with other tools and programs instead of handling files

**Comment by eldritchconundrum** [comment]
Hi,
We already have it, I think it was `-o -`

**Comment by Lutymane** [comment]
Oops, smh I missed the docs saying that you can supply `-` for `stdout` 😳. Maybe worth adding that to `--help` as well

**Comment by Lutymane** [comment]
@eldritchconundrum could you also please help with another question? 

I checked documentation multiple times and didn't find a mention about how using `stdin` for input. I checked sources and found this line: https://github.com/laurentlb/Shader_Minifier/blob/master/src/main.fs#L40
So I suppose `stdin` input is possible but I can't make it to work. Tried `""`, `-` and `stdin` as argument and it always fails with `System.IO.FileNotFoundException`.

Also why is `stdin` wrapped in quotes in source?

**Comment by eldritchconundrum** [comment]
`"stdin"` is the pseudo file name here.
You're searching for `if file = "" then new StreamReader(Console.OpenStandardInput())`
I suppose a `""` argument should do it.

You're right, we could use a line or two in the documentation about that.

**Comment by Lutymane** [comment]
Oh, I figured it, so the file in this case is literally checked for `""` string so to properly pass it (in Powershell at least) I had to use ``"`"`""`` lol, basically supplying `""` as string inside of quotes O_O
