### ISSUE TITLE
fail: incorrect conditional logic as `else` blocks move to new location

### ISSUE THREAD

**Issue by Troid92** [laurentlb/Shader_Minifier#143]
Input:
```
float getNum(float a) {
  if (a > 0.0) {
    if (a > 1.0) return 1.0;
  }
  else return 0.0;
  return a;
}
```
In the above, `getNum(0.5)` returns `0.5` and `getNum(-1.0)` returns `0.`

Shader_Minifier output (text format):
```
float f(float f){if(f>0.)if(f>1.)return 1.;else return 0.;return f;}
```
In the above, `f(0.5)` returns `0.` and `f(-1.0)` returns `-1.0`

Expected output:
```
float f(float f){if(f>0.){if(f>1.)return 1.;}else return 0.;return f;}
```
In the above, `f(0.5)` returns `0.5` and `f(-1.0)` returns `0.`

While this example can be simplified to `clamp(a,0.,1.)`, I did experience this bug in a situation where the logic could not be simplified.

Workarounds:
The best workaround I could find is to use an older version of Shader_Minifier as this is technically a regression.
Otherwise I am not aware of any catch-all solution. In the above example, the conditional logic could be flipped (start with `if (a <= 0.0) return 0.0; else ...`) which would produce the correct result. However, if the current `else` statement had similarly nested `if`s then flipping the branches would no longer work. Adding an empty `else {}` in the inner block will not work as it will be removed by Shader_Minifier.

**Comment by laurentlb** [comment]
Thanks for the nice report!

This seems to be a corner-case where removing the curly braces isn't safe. I suppose we could preserve the curly braces when the inner block is a `if`.

I'm surprised older versions of the Minifier didn't have this bug. We'll need to investigate and see what happened.
