### ISSUE TITLE
0*vec3 gets optimized to 0

### ISSUE THREAD

**Issue by LeStahL** [laurentlb/Shader_Minifier#147]
The shader
```
const vec3 x = 0.*vec3(1.,0.,1.);
```
gets minified to `const vec3 f=0.;`, resulting in compiler errors. Expected behavior would be `const vec3 f=vec3(0.);`.

Interestingly, glslang-validator will validate the output of shader_minifier as correct (?), which makes these kind of issues hard to debug.

Observed on version 1.2.

**Comment by laurentlb** [comment]
It's the same issue as https://github.com/laurentlb/Shader_Minifier/issues/2.

I think we could propagate type information to avoid this kind of bug (at least for the simple cases).

**Comment by laurentlb** [comment]
Closing this issue as I've disabled the `0.*x` optimization (#187).

I'll reintroduce it when we have a way to check the type of expressions.
