### ISSUE TITLE
Support array alternate syntax

### ISSUE THREAD

**Issue by eldritchconundrum** [laurentlb/Shader_Minifier#156]
Shader Minifier accepts `int code[] = int[1](123);`
but it doesn't accept `int[] code = int[1](123);`, which works on shadertoy.

**Comment by laurentlb** [comment]
According to the [spec](https://registry.khronos.org/OpenGL/specs/gl/GLSLangSpec.4.60.pdf):
> An array type can be formed by specifying non-array type followed by an array specifier. All dimensions of such an array specifier must include a size.

From what I understand, `int[] code = int[1](123);` isn't valid, but `int[1] code = int[1](123);` is valid.

As a fun fact, these declarations are equivalent:
```c
vec4 a[3][2]; // size-3 array of size-2 array of vec4
vec4[2] a[3];
vec4[3][2] a;
```

**Comment by laurentlb** [comment]
#159
