### ISSUE TITLE
Array initialization error

### ISSUE THREAD

**Issue by pohar** [laurentlb/Shader_Minifier#16]
Parse error occurs in array initialization.
eg: 
```
const int font[] = int[](
 0x69f99, 0x79797, 0xe111e, 0x79997, 0xf171f, 0xf1711, 0xe1d96, 0x99f99,
```
error message:

> Parse error: Error in /tmp/user_shader_618879533.frag: Ln: 5 Col: 15
> const int font[] = int[](
>               ^
> Expecting: '('

(ps: example taken from: [[SH18] The Human Challenge](https://www.shadertoy.com/view/MttczN) )

**Comment by laurentlb** [comment]
The looks like the bug fixed by https://github.com/laurentlb/Shader_Minifier/commit/b0da99f4341249a915059a7d2ea3d159fbf7e6ae
This should work with release 1.1.6 (https://github.com/laurentlb/Shader_Minifier/releases/tag/1.1.6).

**Comment by pohar** [comment]
Thanks
