### ISSUE TITLE
Renaming conflict with reserved words - minified shader fails to compile

### ISSUE THREAD

**Issue by michalfapso** [laurentlb/Shader_Minifier#167]
With a high number of local variables in the shader, new renamed identifiers get up to `do`, which is a GLSL reserved word and the minified shader fails to compile with some Intel drivers.

A list of reserved words not used for new identifiers would help with that.

Here is such a list in another similar minifier project: https://github.com/flowtsohg/glsl-minifier/blob/3497fbecc1b096ee9733d368f1a2737677ffbd5b/glsl_min.rb#L484
And here are those reserved words with 3 or less letters extracted from that project:
```
u        # this seems like a typo to me, but who knows :)
do
if
in
for
out
int
sin
cos
tan
pow
exp
log
abs
mod
min
max
mix
fma
dot
any
all
not
```

Btw, thanks for this great project!

**Comment by laurentlb** [comment]
Thanks for the report!

This was supposed to be handled here: https://github.com/laurentlb/Shader_Minifier/blob/1d8767549eb5a266e203d4d77e6b6fcc0e0122af/src/parse.fs#L371
I'll investigate later.

I optimistically didn't include any 3-letter keywords, but I guess it might be needed at some point. :)

**Comment by michalfapso** [comment]
I see, thanks @laurentlb!

**Comment by eldritchconundrum** [comment]
I suppose the bug only happens when compiling multiple files. :slightly_smiling_face: 
```
        // TODO: combine from all shaders
        let forbiddenNames = (Seq.head shaders).forbiddenNames
```

**Comment by laurentlb** [comment]
Which version of Shader Minifier are you using?

When I tried to reproduce the error, it skipped `do` as expected:
![image](https://user-images.githubusercontent.com/485572/205463099-b82d28da-4275-4ae0-819f-74e45fdc135e.png)

I've tried also to minify two files at the same time, with no issue.
Do you know how to reproduce the bug?

**Comment by michalfapso** [comment]
I'm so so sorry, you're right, I was using an older version by a mistake. With the current version it works properly as you wrote.
