### ISSUE TITLE
Empty or comments-only Verbatim sections cause System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by rafaelspring** [laurentlb/Shader_Minifier#168]
Minifying the following results in a `System.IndexOutOfRangeException`

`shader_minifier.exe -o C:/somepath/testout.h C:/whatever/test.shader`

test.shader:
```
//[
//blabla
//]

void main(void) {
  gl_FragColor = vec4(1.0);
}
```
Same error when removing the `//blabla` line.
Minifies fine if replacing `//blabla` with `float fooBar() { return 5.0; }`

Comments inside verbatim are important as we use them to declare compile-time variables.
We have our own GLSL compile-time variables system based on `#define` statements, so
```
//[
//CC SOME_COMPILETIME_VAR 0 1 2 3
//]
```
will cause our shader system to create four different shaders from the source, each with `SOME_COMPILETIME_VAR ` defined to a different value.

I'd be more than happy to fix this in the minifier source, however my F# abilities are nonexistent.

**Comment by laurentlb** [comment]
Thanks for the report!
I can reproduce the bug on https://ctrl-alt-test.fr/minifier/

```
//[
//blabla
//]
```
A workaround is to insert a space between the two slashes:

```
//[
/ /blabla
//]
```

I'll take a look at the code later.
