### ISSUE TITLE
Minifier strips closing #else and #endif lines if code path contains return statement.

### ISSUE THREAD

**Issue by rafaelspring** [laurentlb/Shader_Minifier#169]
Minifying the following produces the error:
```
vec4 foobar() { 
#if (SOME_CONSTANT == 0)
  return vec4(texture2D(someTexture, texCoord).rgb, 1.0);
#else
  return vec4(1.0);
#endif
}

void main(void) {
  gl_FragColor = foobar();
}
```

Was able to reproduce it here too https://ctrl-alt-test.fr/minifier/?main

The minifier version 1.1 did not have this bug (however that one had another issue that causes NVIDIA drivers to not accept certain minified GLSL. Seems like it's re-using certain names for variables as well as functions.).

**Comment by laurentlb** [comment]
This is caused by dead-code elimination (the code after a return is removed).

We could either add a flag to disable that optimization, or try to be smarter in presence of `#if` macros.

**Comment by rafaelspring** [comment]
Either would work I guess.
