### ISSUE TITLE
References in #define are not renamed

### ISSUE THREAD

**Issue by KoltesDigital** [laurentlb/Shader_Minifier#19]
Hi,

Minifying

```glsl
uniform float a;
const float b;
#define c (a + b)
```

gives

```glsl
uniform float f;const float o;
#define c (a+b)
```

which breaks the shader. Are `#define`s in your scope? I think it's easy to parse and replace variable names (regexp with word boundaries). Users may purposefully create complex macros, so a new CLI option would disable this replacement.

**Comment by laurentlb** [comment]
This is not always correct. `a` and `b` might be different variables, depending on where the macro is called.

The current recommendation is to avoid using macros. If the shader is compressed in a binary, using macros doesn't necessarily make the binary smaller.

**Comment by KoltesDigital** [comment]
Agreed.
