### ISSUE TITLE
optimization changes the return type of an expression.

### ISSUE THREAD

**Issue by cupe** [laurentlb/Shader_Minifier#2]
perfectly legal lines like:

outColor.rgb = 0.0_(0.5+(0.5_(vec3(1)+n)));

get optimized to

outColor.rgb = .0;

which is not legal anymore.

**Comment by laurentlb** [comment]
Closing this issue as I've disabled the `0.*x` optimization (#187).

I'll reintroduce it when we have a way to check the type of expressions.
