### ISSUE TITLE
A necessary type conversion is removed

### ISSUE THREAD

**Issue by therontarigo** [laurentlb/Shader_Minifier#233]
Shader_Minifier replaces a type constructor with its arguments which are of a different type.

Input:
```GLSL
uniform layout(location=0) ivec4 bctr;
vec2 uv=gl_FragCoord.xy/vec2(bctr.zw);
```
Output:
```GLSL
uniform layout(location=0) ivec4 v;
vec2 m=gl_FragCoord.xy/v.zw;
```

I don't think the responsible optimization is important even in cases that it is valid, since I don't write useless type constructors into my sources, but I didn't see a way to turn it off as a workaround.

**Comment by laurentlb** [comment]
Thanks for the report, the optimization was indeed not a good idea.

I've created a new release with the fix: https://github.com/laurentlb/Shader_Minifier/releases/tag/1.3.4
