### ISSUE TITLE
Array declaration not working

### ISSUE THREAD

**Issue by bmFicg** [laurentlb/Shader_Minifier#243]
I use with shader minifier with OpenGL 4.6 [GLSLangSpec.4.6](https://registry.khronos.org/OpenGL/specs/gl/GLSLangSpec.4.60.html#arrays), but this goes early as [#version150](https://registry.khronos.org/OpenGL/specs/gl/GLSLangSpec.1.50.pdf)
> Quote:
> and as an alternate way of declaring a variable or function parameter.
> float[5] a;
```glsl
out vec4 fragColor;
void main() {
  float result[2] = float[](1., 1.);
  //float[2] result = float[](1., 1.);//not working
  fragColor = vec4(result[0],result[1],1.,1.);
}
```
---
- [x] Current workaround 
```glsl
#define TYPEDEFARRAY float[2]
TYPEDEFARRAY result = float[](1., 1.);
```

**Comment by bmFicg** [comment]
I also use the first syntax for simple array initialization. This is about a function that returns an array, which may be done though value-return. Thanks so far for your effort on the shader minifier; I appreciate it.

```glsl
float[2]func_bank(in float[2]res)
{
    float a = res[0], b = res[1];
    res[0] = a < b ? a : b; // min
    res[1] = a > b ? a : b; // max
    return res;
}

void main()
{
    float test[2] = float[](5., 7.);

    func_bank(test)[0]; // 5
    func_bank(test)[1]; // 7

    /*do something awesome*/
}
```

**Comment by laurentlb** [comment]
It looks like the code is correctly parsed, but the array suffix is missing in the output. I can't do it now, but that should be a one-line fix: https://github.com/laurentlb/Shader_Minifier/blob/master/src/printer.fs#L158
