### ISSUE TITLE
Inline local variables after simplifications

### ISSUE THREAD

**Issue by laurentlb** [laurentlb/Shader_Minifier#248]
```glsl
out vec4 fragColor;

void main() {
  float t = 1.5+(1.+.5); 
  fragColor = vec4(t); 
}
```

The variable `t` was inlined in Minifier 1.3.2, but no longer in Minifier 1.3.4. I don't know what caused the regression. Here is the current output:

```glsl
  float t = 3.;
  fragColor = vec4(t); 
```

**Comment by eldritchconundrum** [comment]
It started working again at some point. I have added a test just in case it comes back.
