### ISSUE TITLE
Shader Minifier crashes and clears input file

### ISSUE THREAD

**Issue by LJ1102** [laurentlb/Shader_Minifier#30]
This little snippet of code causes shader minifier to crash and clear the input file:
```c
const int TEST = 3;
void main () {
  int[5] a = {1,2,3,4,5};
  gl_FragColor = a[TEST];
}
```
I suspect it also took down the server(trying it in the online version) but I didn't confirm this yet due to obvious reasons.

**Comment by laurentlb** [comment]
If I remember correctly, this was an unrelated problem, right?

**Comment by LJ1102** [comment]
The person who reported that the file got cleared (slerpy) couldn't reproduce the issue after multiple tests, feeding the code to the online-version doesn't seem to crash the server anymore either, maybe the server was crashing due to other circumstances not related to the actualy shader code I fed it or there's some kind of race condition?

Either way I fear there's nothing actionable to be done here, sorry.
