### ISSUE TITLE
Linux source files?

### ISSUE THREAD

**Issue by akikoskinen** [laurentlb/Shader_Minifier#5]
In the README.md it says: "_For Linux, I use a newer version of FParsec that I patched manually (some functions in FParsec have changed, which means I need a different parse.fs source file too)_"

Where is this patched FParsec? Is such patches needed any more at all? If they are good are they sent or even accepted upstream?

Where is this different version of parse.fs?

Overall: is there any change to build this project in Linux? What versions of dependencies could work?

**Comment by laurentlb** [comment]
It should build on Linux now (see `compile.bash`).
